rmdir /s /q "./LuaJITLib/Debug"
rmdir /s /q "./LuaJITLib/Release"
rmdir /s /q "./LuaJITLib/x64"
rmdir /s /q "./Encrypt/Release"
rmdir /s /q "./Encrypt/Debug"
rmdir /s /q "./Encrypt/x64"
rmdir /s /q "./VAScan/Release"
rmdir /s /q "./VAScan/Debug"
rmdir /s /q "./VAScan/x64"
rmdir /s /q "./VAScanTest/Release"
rmdir /s /q "./VAScanTest/Debug"
rmdir /s /q "./VAScanTest/x64"
rmdir /s /q "../output/win32"
rmdir /s /q "../output/x64"

del /q ".\3rd-party\lua\luajit\LuaJIT-2.0.5\src\luajit.ilk"
del /q ".\3rd-party\lua\luajit\LuaJIT-2.0.5\src\luajit.pdb"
del /q ".\3rd-party\lua\luajit\LuaJIT-2.0.5\src\luajit.exe"
del /q ".\3rd-party\lua\luajit\LuaJIT-2.0.5\src\vc110.pdb"
del /q ".\3rd-party\lua\luajit\LuaJIT-2.0.5\src\lua51.lib"
del /q ".\3rd-party\lua\luajit\LuaJIT-2.1.0\src\luajit.ilk"
del /q ".\3rd-party\lua\luajit\LuaJIT-2.1.0\src\luajit.pdb"
del /q ".\3rd-party\lua\luajit\LuaJIT-2.1.0\src\luajit.exe"
del /q ".\3rd-party\lua\luajit\LuaJIT-2.1.0\src\vc110.pdb"
del /q ".\3rd-party\lua\luajit\LuaJIT-2.1.0 \src\lua51.lib"
del /q ".\Encrypt\Encrypt.vcxproj.user"
del /q ".\VAScan\VAScan.vcxproj.user"
del /q ".\VAScanTest\VAScanTest.vcxproj.user"
del /q "VAScan.opensdf"
del /q "VAScan.sdf"
del /a:H "VAScan.v11.suo"